fitness_nutrition_websites = [
    {"name": "MyFitnessPal", "url": "https://www.myfitnesspal.com"},
    {"name": "Bodybuilding.com", "url": "https://www.bodybuilding.com"},
    {"name": "Fitness Blender", "url": "https://www.fitnessblender.com"},
    {"name": "Nerd Fitness", "url": "https://www.nerdfitness.com"},
    {"name": "Precision Nutrition", "url": "https://www.precisionnutrition.com"},
    {"name": "Examine.com", "url": "https://examine.com"},
    {"name": "Men's Health", "url": "https://www.menshealth.com"},
    {"name": "Women's Health", "url": "https://www.womenshealthmag.com"},
    {"name": "Runner's World", "url": "https://www.runnersworld.com"},
    {"name": "Muscle & Fitness", "url": "https://www.muscleandfitness.com"},
    {"name": "Shape", "url": "https://www.shape.com"},
    {"name": "Healthline Nutrition", "url": "https://www.healthline.com/nutrition"},
    {"name": "SparkPeople", "url": "https://www.sparkpeople.com"},
    {"name": "Breaking Muscle", "url": "https://breakingmuscle.com"},
    {"name": "T-Nation", "url": "https://www.t-nation.com"},
    {"name": "Eat This, Not That!", "url": "https://www.eatthis.com"},
    {"name": "Born Fitness", "url": "https://www.bornfitness.com"},
    {"name": "ACE Fitness", "url": "https://www.acefitness.org"},
    {"name": "SELF", "url": "https://www.self.com"},
    {"name": "BodyRock", "url": "https://www.bodyrock.tv"},
    {"name": "Nutrition.gov", "url": "https://www.nutrition.gov"},
    {"name": "Greatist", "url": "https://greatist.com"},
    {"name": "Girls Gone Strong", "url": "https://www.girlsgonestrong.com"},
    {"name": "Workout Mommy", "url": "https://workoutmommy.com"},
    {"name": "Tone It Up", "url": "https://www.toneitup.com"},
    {"name": "Muscle for Life", "url": "https://www.muscleforlife.com"},
    {"name": "Barbend", "url": "https://barbend.com"},
    {"name": "Runtastic Blog", "url": "https://www.runtastic.com/blog"},
    {"name": "Fit Bottomed Girls", "url": "https://fitbottomedgirls.com"},
    {"name": "POPSUGAR Fitness", "url": "https://www.popsugar.com/fitness"},
    {"name": "Oxygen Magazine", "url": "https://www.oxygenmag.com"},
    {"name": "Strength Sensei", "url": "https://strengthsensei.com"},
    {"name": "Workout Labs", "url": "https://workoutlabs.com"},
    {"name": "The Fitnessista", "url": "https://fitnessista.com"},
    {"name": "Fit Men Cook", "url": "https://fitmencook.com"},
    {"name": "Blogilates", "url": "https://www.blogilates.com"},
    {"name": "Lean It UP", "url": "https://www.leanitup.com"},
    {"name": "Nutrition Facts", "url": "https://nutritionfacts.org"},
    {"name": "Biolayne", "url": "https://www.biolayne.com"},
    {"name": "Legion Athletics", "url": "https://legionathletics.com"},
    {"name": "Fit Body Boot Camp", "url": "https://fitbodybootcamp.com"},
    {"name": "Athlean-X", "url": "https://athleanx.com"},
    {"name": "Fitness Magazine", "url": "https://www.fitnessmagazine.com"},
    {"name": "Muscle & Strength", "url": "https://www.muscleandstrength.com"},
    {"name": "Reign Body Fuel", "url": "https://reignbodyfuel.com"},
    {"name": "Yoga Journal", "url": "https://www.yogajournal.com"},
    {"name": "Stronger by Science", "url": "https://www.strongerbyscience.com"},
    {"name": "Onnit", "url": "https://www.onnit.com"},
    {"name": "Lift Big Eat Big", "url": "https://liftbigeatbig.com"},
    {"name": "Whole30", "url": "https://whole30.com"}
]
